name: Automated Commit

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Debug Information
        run: echo "::debug::Triggered by ref = ${{github.ref}}"

      - name: Checkout Code
        uses: actions/checkout@v4 # Pastikan menggunakan versi terbaru
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Update Timestamp File
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "===================================" > rain.txt
          echo "           Last Updated            " >> rain.txt
          echo "           $current_time           " >> rain.txt
          echo "===================================" >> rain.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "vilakerlas@gmail.com.com"
          git config user.name "1anode"

      - name: Prepare Commit
        run: |
          commit_messages=("Update: ğŸš€" "Sync: ğŸŒ" "Refine: ğŸ”" "Reboot: ğŸ”„" "Enhance: âœ¨" "Overhaul: ğŸ”§" "Transform: ğŸ”®" "Elevate: â¬†ï¸" "Boost: âš¡" "Polish: âœï¸")
          random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}
          git add rain.txt
          git commit -m "$random_msg - $current_time" || echo "No changes to commit." && exit 1

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "$random_msg - $current_time"
          directory: '.'
          github_token: ${{ secrets.TOKE }}
